spring:
  datasource:
    primary:
      url: jdbc:mysql://conn.thinkinpower.net:13306/platform_admin?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
    quartz:
      url: jdbc:mysql://conn.thinkinpower.net:13306/quartz_admin?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 30
    default-fetch-size: 20
  type-aliases-package: com.ucucs.wxwork.model
  mapper-locations: classpath*:com.ucucs.wxwork/**/*.xml